hash-format = "sha256"

[[files]]
file = "LICENSE"
hash = "9984b97d0d4ecb102a6c98e4111a44c99439d43cfb1207c9eb73ebe1ff8b52e0"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "ca3ae2608987185814c118388f28057f729d866ee1abbc97f3650141d213fa35"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "a12e6ec8be7bfbdd2e8c1713d3094fed8474ca18b8cbfae0b6e4f1bc00921db5"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "5e097f95b8818e0999b4e867351745441f90c9bcf2a9c68cd19d5d708da4a4a1"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "a8f073ab0640d9e501fe3fc95d282306000fd6eab3186fd682269c0d0913b307"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a06ef129798265e0d7249426fb0ed5c506725b0460dc3dfdb975b8978480895e"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "d53b229a5588d33a8dac8682cba4371b22b2cbe2541c7129506cfbd44daaf6f8"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "c23a1be7641341478b09c5c4f835b5e024a246f9e8521e92905bcab0d0e8cce0"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "45abf05e1cc90006aeb65e4e1bbe97da5a1984f547ea8028a077dae68af0ac11"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "408151861cc1b1a4c4e9c8a3550662a2fc36d0ea96ee07b7e96c5d2a6afacf6f"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "816b735b2ad505476201800a99f527e61b392b712b9d20ca9edcce05f412fe87"
metafile = true

[[files]]
file = "mods/forcecloseworldloadingscreen.pw.toml"
hash = "db1b2a280e596ea170ab575abc74ac9da9afdd9d4f8108e330cdcb034f8e4c55"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "13e8a24074dcdab4b26b834f9d3ff8ce56a8aa1e8f743d1d1836d423b9f9a2e1"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "9e7bacd24307639764f3b74ae35a562b6becf2701637b816de0eaae15ab714c0"
metafile = true

[[files]]
file = "mods/inventory-sorting.pw.toml"
hash = "fd8297a04498847c8658dcfdc70e8c85f381097dfe2dac78428d1584d7242031"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "276947b1f9933ca2220a00736aba177e4034ca9a45cad9f258abf762fdb3bb0b"
metafile = true

[[files]]
file = "mods/ixeris.pw.toml"
hash = "10fc881ee3e588b90741540e53e72fcd4d055165bc9021ea362359118e338644"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "9a74f9345a91af6a0e2c1975e1dd1d26cfcae6fb072a3a0d68fd9de110ab6327"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "7f26c8df78d02b1d63a723a3a45b838415126da5296ac67b0414e564da30a421"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "51ff93e279e03cb3cd77a5be0df777cdcd975d35b5149180d9dc724e47168c76"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "e4b9192ce7f54715dde7eb682ebab23aaaac10658b1bd08ba553a5f99b0124d1"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "08b89b53c392b5fa29198418df8598404d93c58eae40d432caed797c828adbd5"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "c5cf55b4ec0c694443ae7769d9d96b7ae69aef8a94e7d74f884014b7f5102234"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "ab6def9d98d3f5bf12f78845bdb770a19d5ca590c571e60184e537ffa14dcbee"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "3cbdb02ff4be022d7e0f9b82cd64a36669d5986d7ed3ddcf7bcdbacc0b1b4b2a"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "565c943b5006c36137a2fe55e4b8433e134c3d1011a37c5f5124cee67b671cb8"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "5beb483696cdddc56fd80223e02293430634c7307a1c8d5d5d29a94c1d9178c9"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "fb952e6a0454ecbcdc40ed90b9cf7a7c8a9f86234f6b753743dfbba32b7e8535"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "986e43ff06d2a79effec6e219aca063d7b53a98096c5f63983f23cf54c11c7e5"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "9d340481c374a20067d1748c1a4991626bce9d7812f0bdb96072cd7a15d35462"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "c073f13897a838e3c409e46b8a1d8cb510d6a6584dd815aeadaf4886f1779513"
metafile = true

[[files]]
file = "mods/symbol-chat.pw.toml"
hash = "51cffb97040d4f52ca24a552d7c4bb2b6be1521e65109946233a67fa9792a17b"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "9ce3767540efbf35e0a0c266040c9879efc9136ec59cd38e06e45b3c3c3e90e0"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
hash = "398015112b0975e3bb42e8ec7afc88a007813dfd4dc7a3a02210bab0522da68a"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "1113d43c39a9866252a83ee50d16aa3ce6fcf749acd84d58b05ca09eba4d187b"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "3ff0c2f005f2523f157b776f0e870494a8e8ec0ff77cb7e965c88b4e2090efdb"
metafile = true
